GET http://localhost:9000/api/v1/search/test
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJleHBpcmVfdGltZSI6MTY1Mzk4NTE2Mzc4OCwibWVtYmVyX25vIjoxMDAwMDAwMDEwNjksImFwcGxpY2F0aW9uX25vIjoxMDAwMn0.llanAiKn7TD1Z__coIGYtG6deOCb4PPnb-TaXvNjkNO0HAs8IZcJtDFiMlIAKQFUCIFDfL4PgLffDmWhmqrgJJVqwbJJoIcDfbAERZBd4TUGQxTrmHBsiW9q8ATeBwhJTKux6gPLwaLJfygWsGkJ6HgGkeWij3iv8S8ZDMhX0uB7zHRoy1ftSIEA47vN8kRMF7iJJsYus7zJS8xspOnKz4zqHLvt4tL5LCDkSjPP30hFghmBZ1XxM91mXppKIbIh