# connection settings
 
# connect to MongoDB using the following URL
mongo-url = "mongodb://10.140.111.150:27017,10.140.111.150:27018"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://10.140.111.18:9200"]
 
# frequently required settings
 
# if you need to seed an index from a collection and not just listen and sync changes events
# you can copy entire collections or views from MongoDB to Elasticsearch
direct-read-namespaces = ["gamewood.board"]
 
# if you want to use MongoDB change streams instead of legacy oplog tailing use change-stream-namespaces
# change streams require at least MongoDB API 3.6+
# if you have MongoDB 4+ you can listen for changes to an entire database or entire deployment
# in this case you usually don't need regexes in your config to filter collections unless you target the deployment.
# to listen to an entire db use only the database name.  For a deployment use an empty string.
change-stream-namespaces = ["gamewood.board"]

# additional settings
 
# generate indexing statistics
#stats = true
# index statistics into Elasticsearch
#index-stats = true
# include 2 automatic fields in the source document indexed into Elasticsearch (oplog_ts, oplog_date)
#index-oplog-time = true
index-as-update = true
 
# propogate dropped collections in MongoDB as index deletes in Elasticsearch
dropped-collections = false
# propogate dropped databases in MongoDB as index deletes in Elasticsearch
dropped-databases = false
 
# resume processing from a timestamp saved in a previous run
resume = true
# do not validate that progress timestamps have been saved
resume-write-unsafe = false
# use a custom resume strategy (tokens) instead of the default strategy (timestamps)
# tokens work with MongoDB API 3.6+ while timestamps work only with MongoDB API 4.0+
resume-strategy = 0
 
# enable clustering mode
#cluster-name = 'HA'
#workers = ["w1","w2"]
 
# print detailed information including request traces
verbose = true

# logs
[logs]
info = "/var/logs/monstache/info.log"
warn = "/var/logs/monstache/warn.log"
error = "/var/logs/monstache/error.log"
trace = "/var/logs/monstache/trace.log"
stats = "/var/logs/monstache/stats.log"

[[script]]
script = """
module.exports = function(doc, ns) {
    doc._meta_monstache = { index: ns.replace(".","-") };
    return doc;
}
"""