stats = true

mongo-url = "mongodb://mongo1:27017,mongo2:27017/gamewood?replicaSet=replication"

elasticsearch-urls = ["http://elasticsearch:9200"]

dropped-collections = false

dropped-databases = false

resume = false

resume-write-unsafe = true

index-as-update = true

index-oplog-time = true

verbose = true

[[script]]
script = """
module.exports = function(doc, ns) {
    doc._meta_monstache = { index: ns.replace(".","-") };
    return doc;
}
"""

[logs]
info = "/Users/yoojjang-mn/search-demo/config/info.log"
trace = "/Users/yoojjang-mn/search-demo/config/trace.log"
error = "/Users/yoojjang-mn/search-demo/config/error.log"
warn = "/Users/yoojjang-mn/search-demo/config/warn.log"